server:
  port: 8010

spring:
  application:
    name: file
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

file:
  upload-dir: uploads/images

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh