server:
  port: 9010
spring:
  application:
    name: notification
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}

  cloud:
    function:
      definition: processSuccessPayment
    stream:
      bindings:
        processSuccessPayment-in-0:
          destination: success-payment
          content-type: application/json
          group: notification-group

      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, refresh